/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Alert: typeof import('./components/Alert.vue')['default']
    Avatar: typeof import('./components/W3n/Avatar.vue')['default']
    Btn: typeof import('./components/Btn.vue')['default']
    Checkbox: typeof import('./components/Form/Field/Checkbox.vue')['default']
    DropFile: typeof import('./components/Form/Field/DropFile.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    Input: typeof import('./components/Form/Field/Input.vue')['default']
    Loader: typeof import('./components/Loader.vue')['default']
    Mnemonic: typeof import('./components/Mnemonic.vue')['default']
    Modal: typeof import('./components/Modal.vue')['default']
    Nav: typeof import('./components/Nav.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./components/Form/Field/Select.vue')['default']
    SelectInput: typeof import('./components/Form/Field/SelectInput.vue')['default']
    Spinner: typeof import('./components/Spinner.vue')['default']
    SvgInclude: typeof import('./components/SvgInclude.vue')['default']
    Textarea: typeof import('./components/Form/Field/Textarea.vue')['default']
    Tooltip: typeof import('./components/Tooltip.vue')['default']
    UploadDid: typeof import('./components/W3n/UploadDid.vue')['default']
    W3nDid: typeof import('./components/W3n/W3nDid.vue')['default']
    W3nProfile: typeof import('./components/W3n/W3nProfile.vue')['default']
    W3nStart: typeof import('./components/W3n/W3nStart.vue')['default']
    WalletAdd: typeof import('./components/Wallet/WalletAdd.vue')['default']
    WalletConnect: typeof import('./components/Wallet/WalletConnect.vue')['default']
    WalletConnectSporran: typeof import('./components/Wallet/WalletConnectSporran.vue')['default']
    WalletSelect: typeof import('./components/Wallet/WalletSelect.vue')['default']
  }
}
